Ars Technica:
  type: html
  url: https://arstechnica.com/ai/
  filename: Ars_Technica
  # rss: https://arstechnica.com/ai/feed/
  # filter_24h: true   # Filter RSS articles to last 24 hours (default: true)
  include:
  - ^https://arstechnica.com/(\w+)/(\d+)/(\d+)/

Bloomberg:
  type: html
  url: https://www.bloomberg.com/ai
  filename: Bloomberg
  include:
  - ^https://www.bloomberg.com/news/
  rss: https://feeds.bloomberg.com/technology/news.rss

Business Insider:
  type: html
  url: https://www.businessinsider.com/tech
  filename: Business_Insider
  exclude:
  - ^https://www.insider.com
  - ^https://www.passionfroot.me

FT:
  type: html
  url: https://www.ft.com/artificial-intelligence
  filename: FT
  include:
  - https://www.ft.com/content/
  rss: https://www.ft.com/artificial-intelligence?format=rss
# https://www.ft.com/technology?format=rss

Feedly AI:
  type: html
  url: https://feedly.com/i/aiFeeds?options=eyJsYXllcnMiOlt7InBhcnRzIjpbeyJpZCI6Im5scC9mL3RvcGljLzMwMDAifV0sInNhbGllbmNlIjoibWVudGlvbiIsInNlYXJjaEhpbnQiOiJ0ZWNobm9sb2d5IiwidHlwZSI6Im1hdGNoZXMifV0sImJ1bmRsZXMiOnsiYWxsRmVlZGx5TW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9LHsidHlwZSI6InB1YmxpY2F0aW9uQnVja2V0IiwiaWQiOiJkaXNjb3Zlcnk6YWxsLXRvcGljcyIsInRpZXIiOiJ0aWVyMSJ9XSwiY3VzdG9tTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvY2F0ZWdvcnkvZ2xvYmFsLmFsbCJ9XSwiYm9hcmRNb2RlIjpbeyJ0eXBlIjoic3RyZWFtIiwiaWQiOiJ1c2VyLzYyZWViYjlmLTcxNTEtNGY5YS1hOGM3LTlhNTdiODIwNTMwOC90YWcvZ2xvYmFsLmFsbCJ9XSwiYW5ub3RhdGVkTW9kZSI6W3sidHlwZSI6InN0cmVhbSIsImlkIjoidXNlci82MmVlYmI5Zi03MTUxLTRmOWEtYThjNy05YTU3YjgyMDUzMDgvdGFnL2dsb2JhbC5hbm5vdGF0ZWQifV19LCJyZWZpbmVNb2RlIjoiY3VzdG9tTW9kZSIsImxhbmd1YWdlcyI6WyJlbiJdfQ
  filename: Feedly_AI
  exclude:
  - ^https://feedly.com
  - ^https://s1.feedly.com
  - ^https://blog.feedly.com
  scroll: 4   # page down times for infinite scroll
  initial_sleep: 20
  scroll_div: "#feedlyFrame"

# Google News:  # started blocking more effectively
# # could try to search news for 'artificial intelligence' with the google API https://proxiesapi.com/articles/fetching-news-articles-with-the-google-news-api-and-python
# # added google news rss feed to feedly
#   type: html
#   click: //*[@aria-label="Artificial intelligence"]
#   include:
#   - ^https://news.google.com/read/
#   scroll: 1
#   filename: Google_News
#   url: https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen
#   rss: https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en

Hacker News:
  type: rss
  url: https://news.ycombinator.com/
  filename: Hacker_News_1
  exclude:
  - https://news.ycombinator.com/
  - https://www.ycombinator.com/
  rss: https://news.ycombinator.com/rss
  minlength: 5

# Hacker News 2:
#   type: html
#   url: https://news.ycombinator.com/?p=2
#   filename: Hacker_News_2
#   exclude:
#   - https://news.ycombinator.com
#   - https://www.ycombinator.com

HackerNoon:
  type: rss
  url: https://hackernoon.com/tagged/ai
  filename: HackerNoon
  exclude:
  - ^https://hackernoon.com/$
  - ^https://hackernoon.com/c$
  - ^https://hackernoon.com/coins$
  - ^https://hackernoon.com/companies$
  - ^https://hackernoon.com/gallery$
  - ^https://hackernoon.com/how-to-gain-followers-and-newsletter-subs-directly-on-hackernoon$
  - ^https://hackernoon.com/login$
  - ^https://hackernoon.com/reader-boot$
  - ^https://hackernoon.com/sitemap.xml$
  - ^https://hackernoon.com/startups$
  - ^https://hackernoon.com/techbeat$
  - ^https://hackernoon.com/why-i-write-on-hacker-noon-nl28335q$
  - ^https://hackernoon.com/writer-signup$
  rss: https://hackernoon.com/tagged/ai/feed

New York Times:
  type: rss
  url: https://www.nytimes.com/section/technology
  filename: New_York_Times
  include:
  - ^https://www.nytimes.com/(\d+)/(\d+)/(\d+)/
  rss: https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
  initial_sleep: 20

# html because otherwise text posts don't have proper title
Reddit:
  type: html
  url: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/?sort=top&t=day
  filename: Reddit
  exclude:
  - ^https://www.reddit.com/user/
  - ^https://www.reddit.com/domain/
  - ^https://chat.reddit.com/
  - ^https://i.redd.it/
  - ^https://redditblog.com/
  - ^https://www.redditinc.com/
  - ^https://www.reddithelp.com/
  - ^https://itunes.apple.com/
  - ^https://play.google.com/
  - ^https?://(?:www\.)?reddit\.com/r/([^/]+)/?$
  - ^https://www.reddit.com/help/
  - ^https://www.reddit.com/contact/
  - ^https://www.reddit.com/rules/
  scroll: 5
  minlength: 8
  rss: https://www.reddit.com/r/AI_Agents+ArtificialInteligence+Automate+ChatGPT+ChatGPTCoding+Futurology+MachineLearning+OpenAI+ProgrammerHumor+accelerate+aiArt+aivideo+artificial+deeplearning+learnmachinelearning+programming+singularity+tech+technews+technology/top/.rss?sort=top&t=day

Techmeme:
  type: html
  url: https://www.techmeme.com/river
  filename: Techmeme
  exclude:
  - ^https://www.techmeme.com
  - ^https://twitter.com/
  - ^https://www.threads.net
  - ^https://www.linkedin.com
  - ^https://mastodon.social
  - ^https://bsky.app
  rss: https://www.techmeme.com/feed.xml

The Register:
  type: rss
  url: https://www.theregister.com/software/ai_ml/
  filename: The_Register
  include:
  - ^https://www.theregister.com/(\d+)/(\d+)/(\d+)/
  rss: https://www.theregister.com/software/ai_ml/headlines.atom

# 400 error for rss from feedparser
The Verge:
  type: html
  url: https://www.theverge.com/ai-artificial-intelligence
  filename: The_Verge
  include:
  - ^https://www.theverge.com/news
  rss: https://www.theverge.com/rss/ai-artificial-intelligence/index.xml

# 400 error for rss from feedparser
VentureBeat:
  type: html
  url: https://venturebeat.com/category/ai
  filename: VentureBeat
  rss: https://venturebeat.com/category/ai/feed/

WSJ:
  type: html
  url: https://www.wsj.com/tech/ai
  filename: WSJ
  rss: https://feeds.a.dj.com/rss/RSSWSJD.xml
# or https://feeds.content.dowjones.io/public/rss/RSSWSJD

Washington Post:
  type: html
  url: https://www.washingtonpost.com/technology/innovations/
  filename: Washington_Post
  include:
  - https://www.washingtonpost.com/(\w+)/(\d+)/(\d+)/(\d+)/
  rss: https://feeds.washingtonpost.com/rss/business/technology

The Guardian:
  type: rss
  url: https://www.theguardian.com/uk/technology
  filename: The_Guardian
  include:
  - https://www.theguardian.com/
  rss: https://www.theguardian.com/uk/technology/rss

NewsAPI:
  type: rest
  url: https://newsapi.org/v2/everything
  filename: NewsAPI
  function_name: fn_extract_newsapi

# to possibly add:
# papers with code trending
# to scale it, would probably pay for newsapi, newscatcher, gnews.io
